In [1]:
import numpy as np

In [2]:
numeros = [1,2,3,4]

In [3]:
array = np.array(numeros)

In [5]:
array

array([1, 2, 3, 4])

# Genera numeros

In [7]:
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

Genera zeros 

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Genera Unos

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

Crear Matrices 

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Numeros aleatorios

In [12]:
np.linspace(0,30,5)

array([ 0. ,  7.5, 15. , 22.5, 30. ])

In [13]:
np.random.randint(0,100,5)

array([39, 92, 23, 71, 65])

Obtener el maximo de un array

In [15]:
array =  np.random.randint(0,100,50)

In [16]:
array

array([ 9, 34, 64, 12,  8, 94, 55, 35, 17, 28, 34, 99, 35, 68, 88, 56,  1,
       48, 51, 16, 13, 48, 76, 75, 66, 15, 60, 75, 23, 70, 62,  5, 58, 77,
       38, 23, 67, 28, 18, 35, 60,  2, 39, 20, 61, 31, 74, 41, 31, 91])

Maximo 

In [17]:
array.max()

99

Para saber la posicion del numero mayor 

In [18]:
array.argmax()

11

Minimo 

In [20]:
array.min()

1

Media 

In [22]:
array.mean()

44.68

Cambiar de dimensiones el array 

In [23]:
array.reshape(10,5)

array([[ 9, 34, 64, 12,  8],
       [94, 55, 35, 17, 28],
       [34, 99, 35, 68, 88],
       [56,  1, 48, 51, 16],
       [13, 48, 76, 75, 66],
       [15, 60, 75, 23, 70],
       [62,  5, 58, 77, 38],
       [23, 67, 28, 18, 35],
       [60,  2, 39, 20, 61],
       [31, 74, 41, 31, 91]])

In [24]:
array

array([ 9, 34, 64, 12,  8, 94, 55, 35, 17, 28, 34, 99, 35, 68, 88, 56,  1,
       48, 51, 16, 13, 48, 76, 75, 66, 15, 60, 75, 23, 70, 62,  5, 58, 77,
       38, 23, 67, 28, 18, 35, 60,  2, 39, 20, 61, 31, 74, 41, 31, 91])

Para que el cambio sea permamente

In [25]:
array = array.reshape(10,5)

In [26]:
array

array([[ 9, 34, 64, 12,  8],
       [94, 55, 35, 17, 28],
       [34, 99, 35, 68, 88],
       [56,  1, 48, 51, 16],
       [13, 48, 76, 75, 66],
       [15, 60, 75, 23, 70],
       [62,  5, 58, 77, 38],
       [23, 67, 28, 18, 35],
       [60,  2, 39, 20, 61],
       [31, 74, 41, 31, 91]])

Recuperar una fila

In [27]:
array[2]

array([34, 99, 35, 68, 88])

Recuperar una columna

Recuperar un elemento del array

In [ ]:
array[2,3]

Filtrar valores de un array

In [30]:
# Declaramos una variable filtro.
filtro = array > 30
array2 = array[filtro]

In [31]:
array2

array([34, 64, 94, 55, 35, 34, 99, 35, 68, 88, 56, 48, 51, 48, 76, 75, 66,
       60, 75, 70, 62, 58, 77, 38, 67, 35, 60, 39, 61, 31, 74, 41, 31, 91])